Importamos libreria

In [1]:
import tensorflow as tf

tf.constant va quedar fijo a lo larog de todo el script o programa

In [2]:
constante=tf.constant([2.0,3,4],dtype=tf.float32, name='Constante1')
print(constante) #va ser un vector con decimales

Tensor("Constante1:0", shape=(3,), dtype=float32)


tf.placeholder es una variable q va etar vacio en un principio pero va ir adquiriendo valores

In [3]:

apartado=tf.placeholder(tf.float32, name='Apartado1')
print(apartado)

Tensor("Apartado1:0", dtype=float32)


tf.variable es una variable q va ir cambiando su valor a los largo de todo el programa

In [4]:
variable=tf.Variable(3,dtype=tf.float32,name='variable1')
print(variable)

Instructions for updating:
Colocations handled automatically by placer.
<tf.Variable 'variable1:0' shape=() dtype=float32_ref>


Creamos una matriz con ceros pero que despues la podriamos usar, [renglones, columnas]

In [5]:

matriz=tf.zeros([3, 4], tf.int32, name='matriz')
print(matriz)

Tensor("matriz:0", shape=(3, 4), dtype=int32)


Una vez descriptas las variables hay q inicializarlas , osea una vez q detallamos nuestra grafica computacional. 

In [6]:
inicializar=tf.global_variables_initializer()
sess=tf.Session()
sess.run(inicializar)
print(sess.run(variable))#aqui nos devuelve lo q ya tenemos definidos/ armado

3.0


In [7]:
multiplicacion=apartado*constante

In [8]:
print(sess.run(multiplicacion,feed_dict={apartado:[[15,10,5]]})) # despues de la coma es por qu no tiene valores


[[30. 30. 20.]]


In [9]:
#Multiplicacion de matrices necesita lleva la forma (M,N)x(N,M)=M,M
a=tf.placeholder(tf.float32, shape=(2,2))
b=tf.placeholder(tf.float32, shape=(2,3))
#(2,2)x(2,3) aca genero grafica computacional
mult=tf.matmul(a,b) # que va multiplicar matrices a y b
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(mult,feed_dict={a:[[1,2],[2,2]],b:[[12,21,4],[3,2,4]] }))

[[18. 25. 12.]
 [30. 46. 16.]]


In [11]:
c=tf.placeholder(tf.float32, shape=(3)) # producto punto entre 2 vectores
d=tf.placeholder(tf.float32, shape=(3)) # el 3es que tiene tres elementos
punto=tf.tensordot(c,d,1)
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(punto,feed_dict={c:[1,2,3],d:[3,2,1]}))

10.0
